//! src/routes/mod.rs
mod get_animal_count_by_district;
mod get_animal_count_by_kind_for_period;
mod get_apiary_count_by_district;
mod get_disposal_count_by_district;
mod get_disposal_count_by_reason;
mod get_enterprise_count_by_district;
mod get_livestock_age_group_count_by_districts;
mod get_livestock_age_group_count_by_pos_councils;
mod get_livestock_count_by_companies;
mod get_livestock_count_by_districts;
mod get_livestock_count_by_pos_councils;
mod get_researches_by_diseases;
mod get_researches_by_districts;
mod get_researches_by_kinds;
mod get_researches_by_pos_councils;
mod get_vaccinations_by_diseases;
mod get_vaccinations_by_districts;
mod get_vaccinations_by_kinds;
mod get_vaccinations_by_pos_councils;
mod health_check;

pub use get_animal_count_by_district::*;
pub use get_animal_count_by_kind_for_period::*;
pub use get_apiary_count_by_district::*;
pub use get_disposal_count_by_district::*;
pub use get_disposal_count_by_reason::*;
pub use get_enterprise_count_by_district::*;
pub use get_livestock_age_group_count_by_districts::*;
pub use get_livestock_age_group_count_by_pos_councils::*;
pub use get_livestock_count_by_companies::*;
pub use get_livestock_count_by_districts::*;
pub use get_livestock_count_by_pos_councils::*;
pub use get_researches_by_diseases::*;
pub use get_researches_by_districts::*;
pub use get_researches_by_kinds::*;
pub use get_researches_by_pos_councils::*;
pub use get_vaccinations_by_diseases::*;
pub use get_vaccinations_by_districts::*;
pub use get_vaccinations_by_kinds::*;
pub use get_vaccinations_by_pos_councils::*;
pub use health_check::*;
